/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
/* eslint-disable */
import type { Item, Table } from 'airtable-ts';

export interface YswsProjectSubmission extends Item {
  id: string,
  repositoryUrl: string | null, // Original field: "Repository URL"
  demoUrl: string | null, // Original field: "Demo URL"
  howDidYouHearAboutThis: string | null, // Original field: "How did you hear about this?"
  whatAreWeDoingWell: string | null, // Original field: "What are we doing well?"
  howCanWeImprove: string | null, // Original field: "How can we improve?"
  firstName: string | null, // Original field: "First Name"
  lastName: string | null, // Original field: "Last Name"
  email: string | null, // Original field: "Email"
  screenshot: string[], // Original field: "Screenshot"
  description: string | null, // Original field: "Description"
  githubUsername: string | null, // Original field: "GitHub Username"
  addressLine1: string | null, // Original field: "Address (Line 1)"
  addressLine2: string | null, // Original field: "Address (Line 2)"
  city: string | null, // Original field: "City"
  stateProvince: string | null, // Original field: "State / Province"
  country: string | null, // Original field: "Country"
  zipPostalCode: string | null, // Original field: "ZIP / Postal Code"
  birthday: number | null, // Original field: "Birthday"
  optionalOverrideHoursSpent: number | null, // Original field: "Optional - Override Hours Spent"
  optionalOverrideHoursSpentJustification: string | null, // Original field: "Optional - Override Hours Spent Justification"
  automationSubmitToUnifiedYsws: boolean, // Original field: "Automation - Submit to Unified YSWS"
  automationError: string | null, // Original field: "Automation - Error"
  automationFirstSubmittedAt: number | null, // Original field: "Automation - First Submitted At"
  automationYswsRecordId: string | null, // Original field: "Automation - YSWS Record ID"
  slackUsername: string | null, // Original field: "Slack Username"
  hoursEstimate: number | null, // Original field: "Hours estimate"
  idvRec: string | null, // Original field: "idv_rec"
  identityVerified: boolean, // Original field: "Identity Verified"
  shippingName: string | null, // Original field: "Shipping Name"
  duplicate: string | null, // Original field: "Duplicate?"
  createdAt: number | null, // Original field: "Created at"
  automationStatus: string | null, // Original field: "Automation - Status"
  tempHold: boolean, // Original field: "Temp hold"
}

export const YswsProjectSubmissionTable: Table<YswsProjectSubmission> = {
  name: 'YSWS Project Submission',
  baseId: 'appPC9Lm5jwA5VIE8',
  tableId: 'tblBQ2aKCQanXJSaa',
  mappings: {
    repositoryUrl: 'fld9BIrlDRnjVL6Ui', // Original field: "Repository URL"
    demoUrl: 'fldPrLiLa12h50Pfy', // Original field: "Demo URL"
    howDidYouHearAboutThis: 'fldB48lyo1VW1pXVR', // Original field: "How did you hear about this?"
    whatAreWeDoingWell: 'fld04xIw0Jg30wTHJ', // Original field: "What are we doing well?"
    howCanWeImprove: 'fldITYrN0KnGjpSeb', // Original field: "How can we improve?"
    firstName: 'fldaQ63WIIhwzJkzv', // Original field: "First Name"
    lastName: 'fldrz5U1lHDLNgsIH', // Original field: "Last Name"
    email: 'fldYCGOtjaGdTkmzR', // Original field: "Email"
    screenshot: 'fldCUW9JyeauwmyLZ', // Original field: "Screenshot"
    description: 'fldIFFkfSli8AFMbD', // Original field: "Description"
    githubUsername: 'fldoGRsCPljvySA84', // Original field: "GitHub Username"
    addressLine1: 'fldDtPb8zPM4CZS2s', // Original field: "Address (Line 1)"
    addressLine2: 'fldgduLK4ImVTE4Ro', // Original field: "Address (Line 2)"
    city: 'fldQoWAVX33mOdLrz', // Original field: "City"
    stateProvince: 'fldYeXjXlNueOhoLw', // Original field: "State / Province"
    country: 'fldSDMKS7YLgmAs07', // Original field: "Country"
    zipPostalCode: 'fld00PyO4JOklsDxj', // Original field: "ZIP / Postal Code"
    birthday: 'fldKVDqNLSfo4rI6z', // Original field: "Birthday"
    optionalOverrideHoursSpent: 'fldvLn9Rh9X9To51y', // Original field: "Optional - Override Hours Spent"
    optionalOverrideHoursSpentJustification: 'fldkai7CLWixkJlc2', // Original field: "Optional - Override Hours Spent Justification"
    automationSubmitToUnifiedYsws: 'fldnGPfLBvqzZb0qd', // Original field: "Automation - Submit to Unified YSWS"
    automationError: 'fldKjQYWPOs9MXTAL', // Original field: "Automation - Error"
    automationFirstSubmittedAt: 'fld8jTyK0OkAxArSw', // Original field: "Automation - First Submitted At"
    automationYswsRecordId: 'fldlMgjMBRaaPnXCv', // Original field: "Automation - YSWS Record ID"
    slackUsername: 'fld9TiRu0JTKaqCbA', // Original field: "Slack Username"
    hoursEstimate: 'fldoOwpxxFpwu49lF', // Original field: "Hours estimate"
    idvRec: 'fld1xMv37PLYw0MbZ', // Original field: "idv_rec"
    identityVerified: 'fldoe0vNhq3NDzEUo', // Original field: "Identity Verified"
    shippingName: 'flduKKNFjhhTUqjFi', // Original field: "Shipping Name"
    duplicate: 'fldIJjzQftBBTRJmN', // Original field: "Duplicate?"
    createdAt: 'fld8ATO6GCzth5mtw', // Original field: "Created at"
    automationStatus: 'fldo6hfBi8RYVaAIT', // Original field: "Automation - Status"
    tempHold: 'fldfr6D14xQjy2m1S', // Original field: "Temp hold"
  },
  schema: {
    repositoryUrl: 'string | null',
    demoUrl: 'string | null',
    howDidYouHearAboutThis: 'string | null',
    whatAreWeDoingWell: 'string | null',
    howCanWeImprove: 'string | null',
    firstName: 'string | null',
    lastName: 'string | null',
    email: 'string | null',
    screenshot: 'string[]',
    description: 'string | null',
    githubUsername: 'string | null',
    addressLine1: 'string | null',
    addressLine2: 'string | null',
    city: 'string | null',
    stateProvince: 'string | null',
    country: 'string | null',
    zipPostalCode: 'string | null',
    birthday: 'number | null',
    optionalOverrideHoursSpent: 'number | null',
    optionalOverrideHoursSpentJustification: 'string | null',
    automationSubmitToUnifiedYsws: 'boolean',
    automationError: 'string | null',
    automationFirstSubmittedAt: 'number | null',
    automationYswsRecordId: 'string | null',
    slackUsername: 'string | null',
    hoursEstimate: 'number | null',
    idvRec: 'string | null',
    identityVerified: 'boolean',
    shippingName: 'string | null',
    duplicate: 'string | null',
    createdAt: 'number | null',
    automationStatus: 'string | null',
    tempHold: 'boolean',
  },
};